branches:
  only:
  - master
language: node_js
sudo: false
node_js: stable
cache:
  directories:
  - node_modules
before_install:
- git config --global user.name "cyio"
- git config --global user.email "ibeceo@gmail.com"
- git clone --branch gh-pages https://github.com/cyio/bsv-navi gh-dist
install:
- yarn
script:
- yarn build
after_script:
- cp -rf dist/* gh-dist/
- cd gh-dist
- cp index.html 404.html
- git add --all
- git commit --message "auto deploy"
- git push "https://cyio:${GITHUB_TOKEN}@${GH_REF}" gh-pages:gh-pages
env:
  global:
  - GH_REF: github.com/cyio/bsv-navi.git
  - secure: NiE6bvlQFNnrRF8U9XFNxT1De25ydIW7g2/eKVYap4gBvv4WXoH1vsZGD9O8AHgk0JUsxYD0DF5sKg3L4jI3T1bzSvoudP2Y5kH0pdUlAlfQnQE+Vb/Z38Oby77pn3tvPWAx2IxF0JOIfVH+PjAfdefT5+M5RLg7KuLQDeir8ag5Au2Vw/7O9H3o81Vcst5Pza9xcgZKd/ib78PGHc5qvdIMBeVUx0kyJ/9xBEZJai+PyPuDy5sfI9y+UNlpvfMpZUIVlZJee2PO6ogsy8t1OyKgYVvuo5Fx57aue5pikLMrxqR1kNuoioNL5aFgldwFd2Eqxkk8l3ET9D4RR2Kmx4fm9hjNbqg/209BZ0KwxjzMeDnHAkYJaXgyR9NJ8dvQhsmDdDcxIse64xaJ7/NxwUvATcQCk37iNFQh/CpdtopLJ2NmEwVp79k0DnIf0XaAFSWAKt/qFhkFy6QzDKacQ5CDmZtsP9aETzs5teFeW3wmEQ/sIOQoxckDlB1tCAJkBKcA/SM/IbS4j7TMJd130XQfhu12rv9tk7snVfdpKQtDh3LifHEFSpOJaZJ2E02SnK3+F2U3dV+4ryZof9CPiulfqrPdH753mETgvnjX32vrtGrx84U4mlfPKRki7ohlAC+ys53GHrMhlDP66pimOcbeJKtOSQibrMfFsmNtqKc=
